// Generated by gencpp from file wifi_exploration/ap_csi.msg
// DO NOT EDIT!


#ifndef WIFI_EXPLORATION_MESSAGE_AP_CSI_H
#define WIFI_EXPLORATION_MESSAGE_AP_CSI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace wifi_exploration
{
template <class ContainerAllocator>
struct ap_csi_
{
  typedef ap_csi_<ContainerAllocator> Type;

  ap_csi_()
    : points()
    , rssi(0.0)  {
    }
  ap_csi_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , rssi(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef double _rssi_type;
  _rssi_type rssi;





  typedef boost::shared_ptr< ::wifi_exploration::ap_csi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wifi_exploration::ap_csi_<ContainerAllocator> const> ConstPtr;

}; // struct ap_csi_

typedef ::wifi_exploration::ap_csi_<std::allocator<void> > ap_csi;

typedef boost::shared_ptr< ::wifi_exploration::ap_csi > ap_csiPtr;
typedef boost::shared_ptr< ::wifi_exploration::ap_csi const> ap_csiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wifi_exploration::ap_csi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wifi_exploration::ap_csi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wifi_exploration::ap_csi_<ContainerAllocator1> & lhs, const ::wifi_exploration::ap_csi_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.rssi == rhs.rssi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wifi_exploration::ap_csi_<ContainerAllocator1> & lhs, const ::wifi_exploration::ap_csi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wifi_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wifi_exploration::ap_csi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wifi_exploration::ap_csi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wifi_exploration::ap_csi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wifi_exploration::ap_csi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_exploration::ap_csi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_exploration::ap_csi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wifi_exploration::ap_csi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a2bfbdb74cfb622759ba8388ef3bb0d";
  }

  static const char* value(const ::wifi_exploration::ap_csi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a2bfbdb74cfb622ULL;
  static const uint64_t static_value2 = 0x759ba8388ef3bb0dULL;
};

template<class ContainerAllocator>
struct DataType< ::wifi_exploration::ap_csi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wifi_exploration/ap_csi";
  }

  static const char* value(const ::wifi_exploration::ap_csi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wifi_exploration::ap_csi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"float64 rssi\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::wifi_exploration::ap_csi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wifi_exploration::ap_csi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.rssi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ap_csi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wifi_exploration::ap_csi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wifi_exploration::ap_csi_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "rssi: ";
    Printer<double>::stream(s, indent + "  ", v.rssi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIFI_EXPLORATION_MESSAGE_AP_CSI_H
